openapi: 3.1.0
info:
  title: Palenca accounts webhooks API
  description: Palenca API
  version: 2.0.0
tags:
- name: webhooks
paths:
  /v1/webhooks:
    get:
      tags:
      - webhooks
      summary: List Webhooks
      operationId: list_webhooks_v1_webhooks_get
      parameters:
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_WebhooksDataResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - webhooks
      summary: Create Webhook
      operationId: create_webhook_v1_webhooks_post
      parameters:
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhookParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_WebhookDataResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/webhooks/{webhook_id}:
    get:
      tags:
      - webhooks
      summary: Retrieve Webhook
      operationId: retrieve_webhook_v1_webhooks__webhook_id__get
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Webhook Id
        name: webhook_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_WebhookDataResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - webhooks
      summary: Update Webhook
      operationId: update_webhook_v1_webhooks__webhook_id__put
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Webhook Id
        name: webhook_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWebhookParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_WebhookDataResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - webhooks
      summary: Delete Webhook
      operationId: delete_webhook_v1_webhooks__webhook_id__delete
      parameters:
      - required: true
        schema:
          type: string
          format: uuid
          title: Webhook Id
        name: webhook_id
        in: path
      - required: false
        schema:
          type: string
          title: X-Api-Key
        name: x-api-key
        in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse_WebhookDataResponse_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/webhooks/timeout:
    post:
      tags:
      - webhooks
      summary: Send Webhook Timeout
      operationId: send_webhook_timeout_v1_webhooks_timeout_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendWebhookTimeoutParams'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ErrorDetailResponse:
      properties:
        message:
          type: string
          title: Message
        location:
          type: string
          title: Location
      type: object
      title: ErrorDetailResponse
    WebhooksDataResponse:
      properties:
        webhooks:
          items:
            $ref: '#/components/schemas/WebhookDataResponse'
          type: array
          title: Webhooks
      type: object
      required:
      - webhooks
      title: WebhooksDataResponse
    CreateWebhookParams:
      properties:
        url:
          type: string
          title: Url
        name:
          type: string
          title: Name
        connect_flow_id:
          type: string
          format: uuid
          title: Connect Flow Id
        is_sandbox:
          type: boolean
          title: Is Sandbox
        sign_request:
          type: boolean
          title: Sign Request
          default: false
        events:
          items: {}
          type: array
          title: Events
          default:
          - '*'
      type: object
      required:
      - url
      - name
      - connect_flow_id
      - is_sandbox
      title: CreateWebhookParams
      example:
        url: https://domain.com/webhook
        name: My webhook
        is_sandbox: true
        sign_request: false
        widget_id: b679c2fb-a096-4c26-a902-245f9bce66d9
        events:
        - '*'
    UpdateWebhookParams:
      properties:
        url:
          type: string
          title: Url
        name:
          type: string
          title: Name
        connect_flow_id:
          type: string
          format: uuid
          title: Connect Flow Id
        is_sandbox:
          type: boolean
          title: Is Sandbox
        sign_request:
          type: boolean
          title: Sign Request
        is_active:
          type: boolean
          title: Is Active
        events:
          items: {}
          type: array
          title: Events
          default:
          - '*'
      type: object
      title: UpdateWebhookParams
      example:
        url: https://domain.com/webhook
        name: My webhook
        is_sandbox: true
        is_active: true
        sign_request: false
        widget_id: b679c2fb-a096-4c26-a902-245f9bce66d9
    BaseResponse_WebhooksDataResponse_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error:
          $ref: '#/components/schemas/ErrorResponse'
        data:
          $ref: '#/components/schemas/WebhooksDataResponse'
      type: object
      title: BaseResponse[WebhooksDataResponse]
      example:
        success: true
        data: {}
        error: {}
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ErrorResponse:
      properties:
        code:
          type: string
          title: Code
        message:
          type: string
          title: Message
        errors:
          items:
            $ref: '#/components/schemas/ErrorDetailResponse'
          type: array
          title: Errors
      type: object
      title: ErrorResponse
    WebhookDataResponse:
      properties:
        connect_flow_id:
          type: string
          format: uuid
          title: Connect Flow Id
        webhook_id:
          type: string
          format: uuid
          title: Webhook Id
        url:
          type: string
          title: Url
        name:
          type: string
          title: Name
        widget_id:
          type: string
          format: uuid
          title: Widget Id
        is_sandbox:
          type: boolean
          title: Is Sandbox
        is_active:
          type: boolean
          title: Is Active
          default: true
        sign_request:
          type: boolean
          title: Sign Request
        private_key:
          type: string
          title: Private Key
      type: object
      required:
      - webhook_id
      - url
      - name
      - is_sandbox
      title: WebhookDataResponse
    SendWebhookTimeoutParams:
      properties:
        account_id:
          type: string
          format: uuid
          title: Account Id
        webhook_id:
          type: string
          format: uuid
          title: Webhook Id
      type: object
      required:
      - account_id
      - webhook_id
      title: SendWebhookTimeoutParams
    BaseResponse_WebhookDataResponse_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error:
          $ref: '#/components/schemas/ErrorResponse'
        data:
          $ref: '#/components/schemas/WebhookDataResponse'
      type: object
      title: BaseResponse[WebhookDataResponse]
      example:
        success: true
        data: {}
        error: {}
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
